# -------------------------------------------------------------
# tasks/main.yml
# -------------------------------------------------------------
- name: Update package cache (Debian)
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'
  tags: [packages]

- name: Update package cache (RedHat)
  ansible.builtin.dnf:
    update_cache: yes
  when: ansible_os_family == 'RedHat'
  tags: [packages]

- name: Install baseline packages (Debian)
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
  when: ansible_os_family == 'Debian'
  tags: [packages]

- name: Install baseline packages (RedHat)
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present
  when: ansible_os_family == 'RedHat'
  tags: [packages]

- name: Install chrony package (Debian)
  ansible.builtin.apt:
    name: "{{ chrony_package_name }}"
    state: present
  when: ansible_os_family == 'Debian'
  tags: [ntp]

- name: Install chrony package (RedHat)
  ansible.builtin.dnf:
    name: "{{ chrony_package_name }}"
    state: present
  when: ansible_os_family == 'RedHat'
  tags: [ntp]

- name: Set timezone
  community.general.timezone:
    name: "{{ common_timezone }}"
  tags: [timezone]

- name: Enable and start chrony (NTP)
  ansible.builtin.service:
    name: "{{ chrony_service_name }}"
    enabled: yes
    state: started
  when: "'chrony' in common_packages"
  tags: [ntp]

- name: Hold current Ubuntu kernel (prevent accidental upgrades)
  ansible.builtin.dpkg_selections:
    name: linux-image-generic
    selection: hold
  when: ansible_os_family == 'Debian'
  tags: [kernel]

- name: Deploy unattended‑upgrades configuration
  ansible.builtin.template:
    src: unattended-upgrades.conf.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
  notify: restart unattended-upgrades
  when: ansible_os_family == 'Debian'
  tags: [security]

- name: Deploy dnf-automatic configuration
  ansible.builtin.template:
    src: dnf-automatic.conf.j2
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart dnf-automatic
  when: ansible_os_family == 'RedHat'
  tags: [security]

- name: Enable and start dnf-automatic timer
  ansible.builtin.service:
    name: dnf-automatic.timer
    enabled: yes
    state: started
  when: ansible_os_family == 'RedHat'
  tags: [security]

- name: Apply sysctl parameters
  ansible.builtin.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop: "{{ common_sysctl | dict2items }}"
  notify: reload sysctl
  tags: [sysctl]


- name: Retrieve xiRAID hardware key
  ansible.builtin.command: ./hwkey
  args:
    chdir: "{{ playbook_dir }}/.."
  register: hwkey_result
  changed_when: false
  failed_when: hwkey_result.rc != 0
  when: xinas_hostname | length == 0
  tags: [hostname]

- name: Set default hostname fact
  ansible.builtin.set_fact:
    xinas_hostname: "xiNAS-{{ hwkey_result.stdout | trim | upper }}"
  when: xinas_hostname | length == 0
  tags: [hostname]

- name: Set system hostname
  ansible.builtin.hostname:
    name: "{{ xinas_hostname }}"
  tags: [hostname]
