doca_distro_series: "ubuntu24.04"
doca_version: "2.9.1"          # or "DGX_latest_DOCA" for always-latest
doca_repo_base: "https://linux.mellanox.com/public/repo/doca"
doca_repo_component: "{{ doca_version }}/{{ doca_distro_series }}/x86_64"

doca_pkgs:
  - doca-ofed          # DKMS-driven kernel stack
  - doca-ofed-userspace

doca_ofed_auto_reboot: false

# Netplan template containing desired InfiniBand names
ib_netplan_template: "/opt/provision/collection/roles/net_controllers/templates/netplan.yaml.j2"
# Location of generated udev rules for InfiniBand
ib_udev_rules_file: "/etc/udev/rules.d/70-ib-names.rules"
