# xiRAID version to install (use 4.x.y). The repo package is auto-derived.
xiraid_version: "4.3.0"

# Version of the repository package
xiraid_repo_version: "1.3.0-1588"

# Target kernel for the repo package (current kernel's major.minor by default)
# Repository packages are named with just the major and minor kernel numbers
# (e.g. `kver.6.8`), so extract those from `ansible_kernel`.
xiraid_kernel: "{{ ansible_kernel | regex_replace('^(\\d+\\.\\d+).*', '\\1') }}"

# Compose repository package name
xiraid_repo_pkg: "xiraid-repo_{{ xiraid_repo_version }}.kver.{{ xiraid_kernel }}_amd64.deb"

# Base URL to Xinnor repository (multi-pack works for 20.04/22.04/24.04)
xiraid_repo_url_base: "https://pkg.xinnor.io/repository/Repository/xiraid/ubuntu/multi-pack"

# Full URL of repository package
xiraid_repo_pkg_url: "{{ xiraid_repo_url_base }}/{{ xiraid_repo_pkg }}"

# List of xiRAID packages; adjust if version scheme changes.
xiraid_packages:
  - xiraid-core

# Whether to reboot automatically after install (usually not required)
xiraid_auto_reboot: false

# Automatically accept xiRAID EULA after installation
xiraid_accept_eula: true
