# =============================================================
# Role: common
# Directory: collection/roles/common/
# =============================================================
#
# -------------------------------------------------------------
# defaults/main.yml
# -------------------------------------------------------------
common_timezone: "Europe/Amsterdam"
common_packages:
  - curl
  - vim
  - htop
  - chrony                # NTP daemon; change to ntp if preferred
  - "{{ 'unattended-upgrades' if ansible_os_family == 'Debian' else 'dnf-automatic' }}"
  - ca-certificates
chrony_service_name: "{{ 'chronyd' if ansible_os_family == 'RedHat' else 'chrony' }}"
chrony_package_name: chrony
common_sysctl:
  net.core.rmem_max: 268435456
  net.core.wmem_max: 268435456
  vm.swappiness: 10
# Hostname for the node. If empty, the role constructs 'xiNAS-HWKEY'.
xinas_hostname: ""
