- name: Build device list string
  ansible.builtin.set_fact:
    _devlist: "{{ item.devices | join(' ') }}"
  tags: [raid_fs, raid]

- name: Calculate data disk count (for RAID5/6 stripe-width)
  ansible.builtin.set_fact:
    _sw: "{{ (item.devices | length) - (item.parity_disks | default(0)) }}"
  tags: [raid_fs, raid]

- name: Create array {{ item.name }}
  ansible.builtin.command: >-
    xicli raid create -n {{ item.name }} -l {{ item.level }}
    -d {{ _devlist }} -ss {{ item.strip_size_kb }}
    {% if item.spare_pool is defined %}-sp {{ item.spare_pool }}{% endif %}
    {% if xiraid_force_metadata | bool %}--force_metadata{% endif %}
  register: raid_create
  changed_when: raid_create.rc == 0
  failed_when:
    - raid_create.rc != 0
    - raid_create.stderr is not search('already exists')
  tags: [raid_fs, raid]

- name: Wait for xiRAID block device /dev/xi_{{ item.name }}
  ansible.builtin.wait_for:
    path: "/dev/xi_{{ item.name }}"
    timeout: 120
  tags: [raid_fs, raid]
