# -------------------------------------------------------------
# handlers/main.yml
# -------------------------------------------------------------
---
- name: reload sysctl
  ansible.builtin.command: sysctl --system

- name: restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted

- name: restart dnf-automatic
  ansible.builtin.service:
    name: dnf-automatic.timer
    state: restarted
