- name: Ensure build dependencies are present
  ansible.builtin.apt:
    name:
      - dkms
      - build-essential
      - linux-headers-{{ ansible_kernel }}
      - libelf-dev
    state: present
  tags: [ofed, deps]

- name: Add Mellanox GPG key
  ansible.builtin.apt_key:
    url: "{{ doca_repo_base }}/GPG-KEY-Mellanox.pub"
    state: present
  tags: [ofed, repo]

- name: Add DOCA-OFED APT repo
  ansible.builtin.apt_repository:
    repo: "deb {{ doca_repo_base }}/{{ doca_repo_component }} /"
    filename: "mellanox-doca"
    state: present
  register: repo_added
  tags: [ofed, repo]

- name: Update APT cache (if repo added)
  ansible.builtin.apt:
    update_cache: yes
  when: repo_added is changed
  tags: [ofed, repo]

- name: Install DOCA-OFED packages
  ansible.builtin.apt:
    name: "{{ doca_pkgs }}"
    state: present
    update_cache: yes
  register: ofed_pkgs
  notify: restart openibd
  tags: [ofed, install]

- name: Reboot if kernel modules built and reboot requested
  ansible.builtin.reboot:
    msg: "Reboot after DOCA-OFED install (role doca_ofed)"
    reboot_timeout: 1200
  when: ofed_pkgs is changed and doca_ofed_auto_reboot | bool
  tags: [ofed, reboot]
