# -------------------------------------------------------------
# handlers/main.yml
# -------------------------------------------------------------
---
- name: update grub on Debian/Ubuntu
  ansible.builtin.command: update-grub
  when: ansible_os_family == 'Debian'

- name: update grub on RedHat
  ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: ansible_os_family == 'RedHat'

- name: rebuild initramfs on Debian/Ubuntu
  ansible.builtin.command: update-initramfs -u -k all
  when: ansible_os_family == 'Debian'

- name: rebuild initramfs on RedHat
  ansible.builtin.command: dracut -f
  when: ansible_os_family == 'RedHat'
